//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAutomationFramework.Framework.API.Services.Omdb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OmdbTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OmdbTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestAutomationFramework.Framework.API.Services.Omdb.OmdbTerms", typeof(OmdbTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episode.
        /// </summary>
        internal static string EPISODE {
            get {
                return ResourceManager.GetString("EPISODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full.
        /// </summary>
        internal static string FULL_PLOT {
            get {
                return ResourceManager.GetString("FULL_PLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json.
        /// </summary>
        internal static string JSON_DATATYPE {
            get {
                return ResourceManager.GetString("JSON_DATATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie.
        /// </summary>
        internal static string MOVIES {
            get {
                return ResourceManager.GetString("MOVIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string PAGE {
            get {
                return ResourceManager.GetString("PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string SERIES {
            get {
                return ResourceManager.GetString("SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string SHORT_PLOT {
            get {
                return ResourceManager.GetString("SHORT_PLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string XML_DATATYPE {
            get {
                return ResourceManager.GetString("XML_DATATYPE", resourceCulture);
            }
        }
    }
}
