name: Code quality control

on: [push,pull_request]

jobs:
  Label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
  Build:
    runs-on: windows-2019
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Build with msbuild
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\C-Sharp_TestAutomationFrameworik\TestAutomationFramework.sln
