name: Code quality control

on: [push,pull_request]

jobs:
  Label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
  Build:
    runs-on: windows-2019
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with .NET
      run: dotnet build --configuration Release
    - name: Test with .NET
      run: dotnet test --verbosity normal -r bin/test-restults/ --logger trx;LogFileName=test.xml --logger html;LogFileName=test.html
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Test Failures - Test Results
        path: bin\test-restults
